#!/usr/bin/env python3
"""Scan master_species.csv for ALL USDA symbols with HasCharacteristics=true.

Writes:
  data/bronze/usda_catalog/lists/haschar_all.txt
  data/bronze/usda_catalog/lists/haschar_all_notes.md
  data/bronze/usda_catalog/lists/haschar_probe_progress.json  (resume)

Excludes nothing by default; optional --exclude-file for symbols already scraped.
"""
from __future__ import annotations

import argparse
import asyncio
import csv
import json
import time
from pathlib import Path

import aiohttp

API = "https://plantsservices.sc.egov.usda.gov/api/PlantProfile?symbol={symbol}"
UA = "BotanicaSeed/0.3 (full HasCharacteristics scan)"


async def check(session, sem, symbol: str) -> tuple[str, bool]:
    async with sem:
        try:
            async with session.get(
                API.format(symbol=symbol), timeout=aiohttp.ClientTimeout(total=25)
            ) as resp:
                if resp.status != 200:
                    return symbol, False
                data = await resp.json(content_type=None)
                return symbol, bool(isinstance(data, dict) and data.get("HasCharacteristics"))
        except Exception:
            return symbol, False


async def main_async(args) -> int:
    master = Path(args.master)
    out = Path(args.out)
    progress_path = Path(args.progress)
    out.parent.mkdir(parents=True, exist_ok=True)

    symbols = [r["symbol"] for r in csv.DictReader(open(master, encoding="utf-8")) if r.get("symbol")]
    exclude = set()
    if args.exclude_file and Path(args.exclude_file).exists():
        exclude = {
            ln.strip()
            for ln in Path(args.exclude_file).read_text(encoding="utf-8").splitlines()
            if ln.strip()
        }

    done = set()
    found: list[str] = []
    if progress_path.exists() and not args.fresh:
        prog = json.loads(progress_path.read_text(encoding="utf-8"))
        done = set(prog.get("checked", []))
        found = list(prog.get("found", []))
        print(f"resume: checked={len(done)} found={len(found)}", flush=True)

    todo = [s for s in symbols if s not in done and s not in exclude]
    print(f"total={len(symbols)} exclude={len(exclude)} todo={len(todo)}", flush=True)

    sem = asyncio.Semaphore(args.concurrency)
    headers = {
        "User-Agent": UA,
        "Accept": "application/json",
        "Referer": "https://plants.usda.gov/",
    }
    t0 = time.time()
    async with aiohttp.ClientSession(headers=headers) as session:
        for i in range(0, len(todo), args.batch):
            batch = todo[i : i + args.batch]
            results = await asyncio.gather(*[check(session, sem, s) for s in batch])
            for sym, ok in results:
                done.add(sym)
                if ok:
                    found.append(sym)
            if (i // args.batch) % 5 == 0 or i + args.batch >= len(todo):
                rate = len(done) / max(time.time() - t0, 1)
                print(
                    f"checked={len(done)} found={len(found)} rate={rate:.1f}/s remaining≈{len(todo)-i-len(batch)}",
                    flush=True,
                )
                progress_path.write_text(
                    json.dumps({"checked": sorted(done), "found": found}, indent=0),
                    encoding="utf-8",
                )

    # merge exclude already-known haschar into found for full list output
    all_found = sorted(set(found) | exclude)
    out.write_text("\n".join(all_found) + "\n", encoding="utf-8")
    notes = Path(args.notes)
    notes.write_text(
        f"""# Full HasCharacteristics scan

- Date: generated by probe_all_haschar.py
- Master symbols: {len(symbols)}
- With HasCharacteristics (this scan + exclude merge): {len(all_found)}
- Newly found this run: {len(found)}
- Checked this run (unique): {len(done)}
- Concurrency: {args.concurrency}
""",
        encoding="utf-8",
    )
    print(f"DONE wrote {out} n={len(all_found)}", flush=True)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--master", default="data/bronze/usda_catalog/master_species.csv")
    ap.add_argument("--out", default="data/bronze/usda_catalog/lists/haschar_all.txt")
    ap.add_argument("--notes", default="data/bronze/usda_catalog/lists/haschar_all_notes.md")
    ap.add_argument(
        "--progress",
        default="data/bronze/usda_catalog/lists/haschar_probe_progress.json",
    )
    ap.add_argument(
        "--exclude-file",
        default="data/bronze/usda_catalog/lists/gate3c_symbols_1000_haschar.txt",
        help="Already-known haschar symbols to merge into final list",
    )
    ap.add_argument("--concurrency", type=int, default=20)
    ap.add_argument("--batch", type=int, default=60)
    ap.add_argument("--fresh", action="store_true")
    return asyncio.run(main_async(ap.parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
